### ISSUE TITLE
Add IceModel data as additional input data

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#124]
There exists some additional data regarding the ice properties at certain depths, here visualized in a figure from the retro paper.

![image](https://user-images.githubusercontent.com/48880272/148553942-d0f0d909-95fe-48f3-85d2-cdb076d2ab8a.png)

Here is a snippet for reading and extracting certain properties:
```

icemodel_filename = "/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/metaprojects/icetray/stable/ice-models/resources/models/spice_3.2.1/icemodel.dat"
depth = []; absorption=[]; scattering =[]
icemodel_file = open(icemodel_filename)
lines = icemodel_file.readlines()
for oneline in lines:
    oneline = oneline.replace("\n","")
    values = oneline.split(" ")
    #print values
    depth.append(float(values[0]))
    scattering.append(float(values[1]))
    absorption.append(float(values[2]))
depth = np.array(depth)
absorption = np.array(absorption)
scattering = np.array(scattering)
```

1. Check whats available as input to the GNN in this file
2. asses if this is natural to incorporate in the current graph structure
3. if 2 == True, add to sqlite pipeline
4.  if 3 is successful, run a benchmark with/without ice data and see if there's a difference in performance/bias

**Comment by asogaard** [comment]
This is super interesting! 🤯   It could also be used to construct graph adjacencies that reflect ice properties, and therefore light propagation, more naturally. Let's definitely look into this.

**Comment by briedel** [comment]
So a few other things that are related are PINNs (Physics Informed Neural Nets), see https://github.com/maziarraissi/PINNs In this case the "physics" can be the light emission model (not so much an issue at low energies), the ice model, hole ice, cable shadow, etc.

If you guys are interested, we worked with NVIDIA before and they are always interested in working with scientists on these things. Let me know and I will put you in contact.

**Comment by RasmusOrsoe** [comment]
Closed by @timephy .
