### ISSUE TITLE
Prepare noise vs. particle event classifier model

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#132]

**Comment by kaareendrup** [comment]
Hi @asogaard can you assign me to this? I don't think I have permission to do it myself

**Comment by BozianuLeon** [comment]
This has been done, a model trained on 5 million level 2 events is saved in @kaareendrup's cluster account. Will soon be applied on the real data campaign SQLite database

**Comment by asogaard** [comment]
Hi @kaareendrup and @BozianuLeon,
Can you confirm that this has indeed been done? Ideally, can you point to the relevant training scripts/model component that allows for training such a classifier? If this is indeed done, feel free to close the issue.

**Comment by RasmusOrsoe** [comment]
@BozianuLeon @kaareendrup

**Comment by MortenHolmRep** [comment]
@asogaard @RasmusOrsoe I am closing this issue. With the implementation of multi-class classification ([example found here](https://github.com/graphnet-team/graphnet/blob/main/examples/train_classification_model_without_configs.py)), this has been done for noise, muons and particles for the 1% burn sample as well as the ~1 day.
Scripts for running on burn sample is done in the in the this [analysis](https://github.com/graphnet-team/analyses/tree/main/multi_classification_on_stop_and_track_muons). Some scripts still exist locally on hep for now.
