### ISSUE TITLE
Build reconstruction chain (I3Tray)

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#135]
As a first benchmark, this should be a simple, sequential chain running on CPU. It should have the following steps/I3Modules:

1. Noise filter. All events have their GNN noise vs. particle event classifier score saved. Only events passing this classifier will pass on to the following steps. 
2. Muon filter. All events have their GNN muon vs. neutrino event classifier score saved. Only events passing this classifier will pass on to the following step.
3. Neutrino PID. Saving all events and their PID scores.

**Comment by asogaard** [comment]
Hi @BozianuLeon,
As this task is assigned to you, I just wanted to check in on the status on this issue: Do we have all of the three above models trained? And have you managed to run these in icetray?

**Comment by BozianuLeon** [comment]
Yes. The three models are trained on L2+DC simulated data, and can be applied in a event filtration process of sorts. This has yet to be run in ice tray/including GNN scores in relevant i3 files. I think this requires more thought into how we want the GNN output to be visible/retrievable in the relevant i3 files, something I'm sure we can discuss.

**Comment by RasmusOrsoe** [comment]
@asogaard with the introduction of i3 functionality in #416 - perhaps we can close this?
