### ISSUE TITLE
List and prioritise possible applications/use cases

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#21]
Proposal by @asogaard:

*Graph-level classification:*
**Either** topological, inspired by Naoko's talk at the fall CM 2021 [1]:
* Skimming (<img src="https://render.githubusercontent.com/render/math?math=\mu">)
* Stopping track (<img src="https://render.githubusercontent.com/render/math?math=\mu">)
* Throughgoing track (<img src="https://render.githubusercontent.com/render/math?math=\mu">)
* Starting track (<img src="https://render.githubusercontent.com/render/math?math=\nu_{\mu}">)
* Cascade (<img src="https://render.githubusercontent.com/render/math?math=\nu_{\e}/\nu_{\tau}">)
* Double-bang cascade (<img src="https://render.githubusercontent.com/render/math?math=\nu_{\tau}">)
* Noise

**or** by process:

* <img src="https://render.githubusercontent.com/render/math?math=\mu"> (throughgoing or stopping track)
* <img src="https://render.githubusercontent.com/render/math?math=\nu_{e}"> (cascade)
* <img src="https://render.githubusercontent.com/render/math?math=\nu_{\mu}"> (starting track)
* <img src="https://render.githubusercontent.com/render/math?math=\nu_{\tau}"> (cascade, double-bang)
* Noise

Specific classification tasks will then be concerned with (a subset of) these categories. Which categories are relevant depend on the detector (e.g. <img src="https://render.githubusercontent.com/render/math?math=\nu_{e}"> vs. <img src="https://render.githubusercontent.com/render/math?math=\nu_{\tau}"> not relevant/possible for IceCube-86) and the reconstruction level (e.g. <img src="https://render.githubusercontent.com/render/math?math=\nu_{*}"> vs. <img src="https://render.githubusercontent.com/render/math?math=\mu"> more relevant than flavour classification at earlier filtering levels).

*Graph-level regression:*
* Neutrino reconstruction

*Node-level classification:*
* Hit cleaning

*Additional/techniques:*
* Training to mitigate systematic uncertainties (including variations in training, or using adversarial training)
* General pre-training on surrogate task (cf. BERT)
_____________________
[1] https://events.icecube.wisc.edu/event/143/contributions/7805/attachments/6196/7509/CollaborationMeetingFall2021.pdf

**Comment by RasmusOrsoe** [comment]
One big classification task is muon/neutrino/noise!

**Comment by asogaard** [comment]
Yes, definitely, @RasmusOrsoe! Will update original comment to reflect this.

**Comment by asogaard** [comment]
Ping @RasmusOrsoe
