### ISSUE TITLE
Specify setuptools versions

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#230]
We have a confirmed issue, courtesy of @TGarfield17, where the `graphnet` package won't install with `setuptools==62.6.0` despite the `setup.py` file stating that this should be supported. The problem is solved by downgrading to `setuptools==59.5.0`, but we should:

- [ ] Understand why this error occurs.
- [ ] Identify the version of `setuptools` that will install without problems.
- [ ] Update the install requirements and instructions to reflect this.

**Comment by MortenHolmRep** [comment]
@asogaard Is this issue still relevant?
A newer version of setuptools (67.4.0) exist that does not cause this issue.
Often an installation issue can be resolved by running `pip install setuptools --upgrade`

**Comment by asogaard** [comment]
Hi @MortenHolmRep,
If recent versions `setuptools` doesn't lead to this issue, then it seems the problem was due to something in less-than-recent versions of that package. In that case I'd say you're OK to close this issue — we can always reopen if it happens again. :)
