### ISSUE TITLE
Implement pointing reconstruction

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#254]
For pointing-type analysis, joint zenith and azimuth reconstruction is quite usefull. So far we have done zenith and azimuthal reconstruction separately.

**Comment by RasmusOrsoe** [comment]
I think this is solved with #308 ?

**Comment by asogaard** [comment]
I think so, yes! Because the MSE and LogCosh losses, e.g., should work also in the absence of global pooling. I'll go ahead and close this. Thanks for the keen eye, @RasmusOrsoe! :)
