### ISSUE TITLE
Present GraphNeT at 5 conferences or international workshops

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#286]
- [ ] Presenter Name, "Title." Venue (year)
- [ ] Presenter Name, "Title." Venue (year)
- [ ] Presenter Name, "Title." Venue (year)
- [ ] Presenter Name, "Title." Venue (year)
- [ ] Presenter Name, "Title." Venue (year)

**Comment by RasmusOrsoe** [comment]
ACAT
