### ISSUE TITLE
Clean up dynedge.py

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#294]
**Is your feature request related to a problem? Please describe.**
the file contains three versions of dynedge; `dynedge` (low energy / default), `dynege_V2` (Upgrade / High energy), `dynedge_V3` (pulsemap cleaning) each representing different requirements for the model in domain specific applications. 

The naming is confusing and it's not clear to the user which version to choose.

**Describe the solution you'd like**
We should gather these three use cases into a single model (default to `dynedge`). We could introduce an argument `node_aggregations: List[str] = ['min', 'max', 'avg', 'sum']` where the user can specify which many-to-one projections are kept. This allows us to merge `dynedge` and `dynedge_V2`. Then we can come up with an elegant way of toggle on/off the "node aggregation" and "read-out" sections based on either user arguments or something else. Perhaps @asogaard has an elegant idea.

**Comment by asogaard** [comment]
I can take this, but will also need to merge with #297
