### ISSUE TITLE
Northeren Tracks: Gaussian-ish Input Features

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#324]
**What is benchmarked**
Is there a difference in zenith and azimuthal performance, if we adjust the preprocessing of input variables from `TWSRTHVInIcePulsesIC` ? 

**Target variables used for evaluation**
zenith, azimuth

**Step-by-step** 

1. Make a fresh branch
2.  In this fresh branch, make a new `Detector` that accepts a fitted `sklearn.preprocessing`  scaler as input, such that the `_forward` function uses this fitted scaler to scale the input variables (instead of the hard-coded choice). 
3. Extract the constants.FEATURES variables from `TWSRTHVInIcePulsesIC` for events specified in the training selection from `benchmark.py`. Conceptual code snippet for extracting this is below. You might have to add randomly sub-sample events in `training_selection` to avoid blowing out your RAM.
```
import sqlite3
import pandas as pd

database = 'path_to_database/database.db'
training_selection = pd.read_csv('path_to_training_selection.csv')
input_features = ..
with sqlite3.connect(database) as con:
     query = f'select {input_features} from TWSRTHVInIcePulsesIC where event_no in {str(tuple(training_selection['event_no']}'
     features = pd.read_sql(query,con)
```
4. Fit a [sklearn.preprocessing.QuantileTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.QuantileTransformer.html) where `output_distribution = normal` to the input features.
5. Verify that the distribution of input variables is similar to what is shown in the attached picture. 
![billede](https://user-images.githubusercontent.com/48880272/198015593-c3bb9a2a-f404-4f11-9708-e4f303c56c02.png)
6. Open `benchmark.py` with original settings, and change the detector to your custom detector class, and give it your fitted quantile transformer.
8. Run the modified training script for zenith and azimuthal regression with the new detector class. Consult logs to see if the training converged within the specified number of epochs.

**Benchmark deliverance**
Reply to this issue with two plots and attach the modified training script and other relevant changes.  Each plot is a `matplotlib.pyplot.subplots` figure, where the upper plot shows resolution, and the bottom plot shows the relative improvement. See attached example.

1. zenith resolution vs. true energy with curves from `dynedge baseline` and `dynedge with quantile transformer`. Plot has relative improvement shown in the bottom.
2. azimuth resolution vs. true energy with curves from `dynedge baseline` and `dynedge with quantile transformer`. Plot has relative improvement shown in the bottom.

 Relative improvement of the modification w.r.t. the baseline is given by (`relative improvement = (1 - resolution_modification/resolution_baseline)*100`). 

Example Figure

![billede](https://user-images.githubusercontent.com/48880272/197970973-7a67c472-81bb-4780-8bb6-4746902c51d3.png)

**Comment by Peterandresen12** [comment]
Hi all

I have completed the issue, but it was no great success. The fitted quantile transformer looks like this: 

**Transformed inputs using** [sklearn.preprocessing.QuantileTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.QuantileTransformer.html) 
![Std_scalerhistograms_scaled_and_not_scaled](https://user-images.githubusercontent.com/80513173/205587464-dccdb197-98b6-47b7-87a5-f98d902bec7f.png)

I have tried increasing the number of quantiles to get rid of the two outlier bins in first two histograms below to the left, but did not succeed. I also tried scaling each feature down by a factor of 1000 and then fitting a quantile transformer, which also did not remove the outlier bins. 

I then made a detector which accepts a fitted quantile transformer (see code in the bottom). I trained with the standard number of 50 epochs with 5 patience, but for the zenith this did not converge, so I also tried training both with 100 epochs and 15 patience. Neither results were a success. The (extended versions) are simple the ones that were trained with a max of 100 epochs. 

**Zenith angular resolution against benchmark:**
![std_scaler_Zenith_resolution_new_dynedge](https://user-images.githubusercontent.com/80513173/205588511-b7b04785-2262-4ad9-83fd-59c9b01c7ce4.png)

**Azimuth angular resolution against benchmark:**
![std_scaler_Azimuth_resolution_new_dynedge](https://user-images.githubusercontent.com/80513173/205588546-22c8586a-5b26-44b5-83d8-bf25d21c6d78.png)


**Code used to make and fit and save the quantile transformer**
```
import sqlite3
import pandas as pd
#from graphnet.data.constants import FEATURES, TRUTH
from sklearn.preprocessing import QuantileTransformer
import matplotlib.pyplot as plt
import numpy as np
from pickle import dump, load

print(0)
outdir = "/groups/icecube/peter/storage/northern_tracks/Plotting/Std_scaler/"
database = "/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/data/dev_northern_tracks_full_part_1.db"
train_selection = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_train_selection.csv').reset_index(drop = True)['event_no'].ravel().tolist()

number = 50000

train_selection_sample = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_train_selection.csv').sample(n=number).reset_index(drop = True)['event_no'].ravel().tolist()
print(1)
print(train_selection_sample[:10])

features_names = ['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area']

load_feature_sample = True
load_scaler = False

if not load_feature_sample:
    #input_features = FEATURES.DEEPCORE , rde, pmt_area
    with sqlite3.connect(database) as con:
        query = f"""
        SELECT
            dom_x, dom_y, dom_z, dom_time, charge
        FROM 
            TWSRTHVInIcePulsesIC
        WHERE
            event_no in {str(tuple(train_selection_sample))} ;
        """
        features = pd.read_sql(query,con)

    features.to_csv('test_features.csv',index=False)
else:
    features = pd.read_csv('test_features.csv')

print(np.shape(features))
    
print(2)
print(features.head(5))

#features = features/1000

if not load_scaler:
    scaler = QuantileTransformer(output_distribution='normal',n_quantiles = 100000)
    scaler.fit(features)
    dump(scaler, open('std_scaler.pkl', 'wb'))
else:
    scaler = load(open('std_scaler.pkl', 'rb'))


transformed_features = scaler.transform(features)
print(np.shape(transformed_features))
print(3)

bin_nr = 50
fig, axs = plt.subplots(2,5,sharex=False,figsize=(16, 8))
for i in range(5):
    axs[0,i].hist(features[features_names[i]],bins=bin_nr,label=features_names[i])
    axs[0,i].set_xlabel(features_names[i])
for i in range(5):
    axs[1,i].hist(transformed_features[:,i],bins=bin_nr,label=features_names[i])
    axs[1,i].set_xlabel(features_names[i])


axs[0,0].set_ylabel('Not scaled')
axs[1,0].set_ylabel('Scaled')

fig.tight_layout()

fig.savefig(outdir + 'histograms_scaled_and_not_scaled.png')
```

**Code used to create new detector class, should be added in file icecube.py**
```
"""IceCube-specific `Detector` class(es)."""

import torch
from torch_geometric.data import Data
from typing import List
from graphnet.utilities.config.model_config import save_config
from graphnet.models.graph_builders import GraphBuilder
from graphnet.models.components.pool import (
    group_pulses_to_dom,
    group_pulses_to_pmt,
    sum_pool_and_distribute,
)
from graphnet.data.constants import FEATURES
from graphnet.models.detector.detector import Detector

import pickle


class IceCube_scaler(Detector):
    """`Detector` class for IceCube-86."""

    # Implementing abstract class attribute
    features = FEATURES.ICECUBE86

    @save_config
    def __init__(
        self,scaler:str, graph_builder: GraphBuilder, scalers: List[dict] = None
    ):
        # Base class constructor
        super().__init__(graph_builder,scalers)
        
        self._scaler = pickle.load(open(scaler, 'rb'))

    def _forward(self, data: Data) -> Data:
        """Ingests data, builds graph (connectivity/adjacency), and preprocesses features.

        Args:
            data (Data): Input graph data.

        Returns:
            Data: Connected and preprocessed graph data.
        """

        # Check(s)
        self._validate_features(data)

        # Preprocessing
        x_numpy = data.x.detach().cpu().numpy()

        data.x[:, :5] = torch.tensor(
            self._scaler.transform(x_numpy[:, :5])
        ).type_as(data.x)

        data.x[:, 5] -= 1.25  # rde
        data.x[:, 5] /= 0.25
        data.x[:, 6] /= 0.05  # pmt_area

        return data
```


**Code used to train the model:**

```
import os
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import EarlyStopping
from pytorch_lightning.loggers import WandbLogger
import torch
from torch.optim.adam import Adam
import pandas as pd
from graphnet.training.loss_functions import VonMisesFisher2DLoss
from graphnet.data.constants import FEATURES, TRUTH
from graphnet.models import StandardModel
from graphnet.models.detector.icecube import IceCubeDeepCore, IceCube_scaler
from graphnet.models.gnn.dynedge import DynEdge
from graphnet.models.graph_builders import KNNGraphBuilder
from graphnet.models.task.reconstruction import ZenithReconstructionWithKappa, AzimuthReconstructionWithKappa
from graphnet.training.callbacks import ProgressBar, PiecewiseLinearLR
from graphnet.training.utils import (
    get_predictions,
    make_dataloader,
    save_results,
)
from graphnet.utilities.logging import get_logger

logger = get_logger()

# Configurations
torch.multiprocessing.set_sharing_strategy("file_system")

# Constants
features = FEATURES.DEEPCORE
truth = TRUTH.DEEPCORE[:-1]
# Make sure W&B output directory exists
WANDB_DIR = "./wandb/"
os.makedirs(WANDB_DIR, exist_ok=True)



def train(config,wandb_logger):
    train_selection = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_train_selection.csv').reset_index(drop = True)['event_no'].ravel().tolist()
    validation_selection = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_validate_selection.csv').reset_index(drop = True)['event_no'].ravel().tolist()
    test_selection = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_test_selection.csv').reset_index(drop = True)['event_no'].ravel().tolist()

    std_scaler_dir = '/groups/icecube/peter/workspace/northern_tracks/std_scaler.pkl'

    # Log configuration to W&B
    wandb_logger.experiment.config.update(config)

    # Common variables
    logger.info(f"features: {features}")
    logger.info(f"truth: {truth}")

    training_dataloader = make_dataloader(db = config['db'],
                                            selection = train_selection, #config['train_selection'],
                                            pulsemaps = config['pulsemap'],
                                            features = features,
                                            truth = truth,
                                            batch_size = config['batch_size'],
                                            num_workers = config['num_workers'],
                                            shuffle = True)

    validation_dataloader = make_dataloader(db = config['db'],
                                            selection = validation_selection, #config["validation_selection"],
                                            pulsemaps = config['pulsemap'],
                                            features = features,
                                            truth = truth,
                                            batch_size = config['batch_size'],
                                            num_workers = config['num_workers'],
                                            shuffle = False)

    test_dataloader = make_dataloader(db = config['db'],
                                            selection = test_selection, #config["test_selection"],
                                            pulsemaps = config['pulsemap'],
                                            features = features,
                                            truth = truth,
                                            batch_size = config['batch_size'],
                                            num_workers = config['num_workers'],
                                            shuffle = False)
    # Building model
    detector = IceCube_scaler(
        std_scaler_dir,
        graph_builder=KNNGraphBuilder(nb_nearest_neighbours=8),
    )
    gnn = DynEdge(
        nb_inputs=detector.nb_outputs,
        nb_neighbours = config["nb_neighbors"],
        global_pooling_schemes = ['min', 'max', 'mean'],
        add_global_variables_after_pooling=True,
    )
    
    if config["target"] =='zenith':
        task = ZenithReconstructionWithKappa(
            hidden_size=gnn.nb_outputs,
            target_labels=config["target"],
            loss_function=VonMisesFisher2DLoss(),
        )

    elif config["target"] == 'azimuth':
        task = AzimuthReconstructionWithKappa(
            hidden_size=gnn.nb_outputs,
            target_labels=config["target"],
            loss_function=VonMisesFisher2DLoss(),
        )

    model = StandardModel(
        detector=detector,
        gnn=gnn,
        tasks=[task],
        optimizer_class=Adam,
        optimizer_kwargs={"lr": 1e-03, "eps": 1e-03},
        scheduler_class=PiecewiseLinearLR,
        scheduler_kwargs={
            "milestones": [
                0,
                len(training_dataloader) / 2,
                len(training_dataloader) * config["n_epochs"],
            ],
            "factors": [1e-2, 1, 1e-02],
        },
        scheduler_config={
            "interval": "step",
        },
    )

    # Training model
    callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=config["patience"],
        ),
        ProgressBar(),
    ]

    trainer = Trainer(
        default_root_dir=f'~/{config["run_name"]}',
        accelerator=config["accelerator"],
        devices=config["devices"],
        max_epochs=config["n_epochs"],
        callbacks=callbacks,
        log_every_n_steps=1,
        logger=wandb_logger,
    )

    try:
        trainer.fit(model, training_dataloader, validation_dataloader)
    except KeyboardInterrupt:
        logger.warning("[ctrl+c] Exiting gracefully.")
        pass

    # Predict on Test Set and save results to file
    results = get_predictions(
        trainer = trainer,
        model = model,
        dataloader = test_dataloader,
        prediction_columns =[config["target"] + "_pred", config["target"] + "_kappa"],
        additional_attributes=[config["target"], "event_no", "energy"],
    )
    save_results(config["db"], config["run_name"] + '_test_set', results, config["archive"], model)

    # Predict on Validation Set and save results to file
    results = get_predictions(
        trainer = trainer,
        model = model,
        dataloader = validation_dataloader,
        prediction_columns =[config["target"] + "_pred", config["target"] + "_kappa"],
        additional_attributes=[config["target"], "event_no", "energy"],
    )
    save_results(config["db"], config["run_name"] + '_validation_set', results, config["archive"], model)

# Main function definition
def main():
    for target in ['azimuth']:#['zenith', 'azimuth']:


        pulsemap = 'TWSRTHVInIcePulsesIC'
        nb_neighbours = 8
        n_epochs = 50
        archive = "/groups/icecube/peter/storage/northern_tracks/Output/Baseline"
        tag = 'Std_scaler'
        run_name = f"dynedgev2_{tag}_{target}_{pulsemap}_k={nb_neighbours}_epochs={n_epochs}"
        
        # Initialise Weights & Biases (W&B) run
        wandb_logger = WandbLogger(
        name=run_name,
        project="NortherenTracks_Benchmark",
        entity="graphnet-team",
        save_dir=WANDB_DIR,
        log_model=True
        )
        # Selections
        #train_selection = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_train_selection.csv').reset_index(drop = True)['event_no'].ravel().tolist()
        #validation_selection = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_validate_selection.csv').reset_index(drop = True)['event_no'].ravel().tolist()
        #test_selection = pd.read_csv('/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/selections/benchmark_test_selection.csv').reset_index(drop = True)['event_no'].ravel().tolist()

        # Configuration
        config = {
            "db": "/groups/icecube/petersen/GraphNetDatabaseRepository/northeren_tracks/dev_northern_tracks_full_part_1/data/dev_northern_tracks_full_part_1.db",
            #"train_selection": train_selection,
            #"test_selection": test_selection,
            #"validation_selection": validation_selection,
            "pulsemap": pulsemap,
            "batch_size": 512,
            "num_workers": 20,
            "accelerator": "gpu",
            "devices": [0],
            "target": target,
            "n_epochs": n_epochs,
            "patience": 5,
            "archive": archive,
            "run_name": run_name,
            "nb_neighbors": nb_neighbours,
            }

        
        train(config,wandb_logger)
        wandb_logger.finalize("success")
# Main function call
if __name__ == "__main__":
    main()
```

**Comment by RasmusOrsoe** [comment]
@Peterandresen12 following our chat last Tuesday, could you try to repeat this but where 

1. `dom_x, dom_y, dom_z` has been scaled with `RobustScaler(unit_variance = True)`
2. `dom_time` and `charge` has been scaled using `QuantileTransformer(output_distribution = 'normal')`

While `RobustScaler` scales each dimension independently, these transformations are collectively isomorphic and should therefore preserve the geometry.

**Comment by RasmusOrsoe** [comment]
Hey @Peterandresen12 thanks for sharing these plots. 

Well, ain't that annoying....

First, can you confirm that "_ as normal_" means that the variables were scaled with the scaling in the IceCube86 detector class?

If so, I see three possibilities

1. We're looking at effects we don't understand
2. The results are dominated by stochasticity from the training / sub-optimal learning rate configuration
3. A bug in the code

I suspect **2.** is quite likely. I think so because, from your plots, we see improvements in resolution for "std scaler position only" for both variables while "std scaler all" shows inferior resolutions for zenith but basically no difference for azimuth.  I would have expected both azimuth and zenith to show the same relative improvements. I think this is also further rationalized by the fact that we struggle with convergence a little bit on this dataset. 

However, it could be that this test tells us that zenith and azimuth doesn't depend equally much on `dom_time` and that the Gaussian scaling of time somehow is not a good idea (which merits 1.).

In order to make sense of this, could I persuade you to include in this thread some snapshots of the loss vs. iterations for the models above?

**Comment by Peterandresen12** [comment]
Hey @RasmusOrsoe 

yes "_ as normal_" means that the variables were scaled with the scaling in the IceCube86 detector class.

Good thing you suggested it, I found that I had missed two things. The **Std scaler position INCLUDED and Std scaler position EXCLUDED , did not converge even when extending to 75 epochs, patience 10 (can be seen below). I am not sure if it would improve to extend, since it looks pretty flat. Off course that is a very subjective statement haha, so I can can try to extend to 100 epochs and 10 patience for those two if you like :-)**  

Below are the validation loss, where I highlight the lowest value. Overall the validation losses matches the plots above I think, but they also show that the difference in loss values is quite small.

First for **Zenith!**
**Baseline**
![image](https://user-images.githubusercontent.com/80513173/208384352-cf46e2e9-6f93-4b21-904d-f95651d035f2.png)


**Std scaler all - did not converge for 50 epochs, patience 5** 
![image](https://user-images.githubusercontent.com/80513173/208384533-0a664375-a760-4589-8a9a-918b786f13eb.png)


**Std scaler all - did converge for 75 epochs, patience 10** 
![image](https://user-images.githubusercontent.com/80513173/208384691-e6e0b703-e2cb-48a0-9425-162b833587c2.png)


**Std scaler position EXCLUDED - did not converge for 50 epochs, patience 5** 
![image](https://user-images.githubusercontent.com/80513173/208384827-8a15ae24-7d0b-44a7-a062-f234be02a4c3.png)


**Std scaler position  EXCLUDED - did not converge for 75 epochs, patience 10 either(I thought it had)** 
![image](https://user-images.githubusercontent.com/80513173/208384960-701e4ce0-4ad3-4e99-acb3-e3da12c5495a.png)


**Std scaler position INCLUDED - did not converge for 50 epochs, patience 5** 
![image](https://user-images.githubusercontent.com/80513173/208385461-890ca26f-3d83-4003-b305-ebc3c41f26d9.png)


**Std scaler position  INCLUDED- did not converge for 75 epochs, patience 10 either(I thought it had)** 
![image](https://user-images.githubusercontent.com/80513173/208385688-a690ad7f-6b4c-4e23-b086-5ec0849dcb24.png)

Then for **Azimuth**
**Baseline**
![image](https://user-images.githubusercontent.com/80513173/208387452-adc837c8-70ab-469d-8f04-e7662e14c060.png)


**Std scaler all - 50 epochs, patience 5** 
![image](https://user-images.githubusercontent.com/80513173/208387561-561d0b9a-b112-4bb8-ac42-8b5387061e9f.png)


**Std scaler position EXCLUDED -  50 epochs, patience 5** 
![image](https://user-images.githubusercontent.com/80513173/208387649-4bc7f8dd-d949-4b2a-b5b3-f508cf3d62c2.png)


**Std scaler position INCLUDED - 50 epochs, patience 5** 
![image](https://user-images.githubusercontent.com/80513173/208387706-022fd892-5b82-4e0d-9d14-3e0f0b4f40d6.png)
