### ISSUE TITLE
Northeren Tracks: Doubling and halfing k

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#327]
**What is benchmarked**
Is there a difference in zenith and azimuthal performance, if we half or double the number of neighbours? 

**Target variables used for evaluation**
zenith, azimuth

**Step-by-step** 

1. Open `benchmark.py` with original settings and update the code that originally says

```
def main():
    for target in ['zenith', 'azimuth']:
        pulsemap = 'TWSRTHVInIcePulsesIC'
        nb_neighbours = 8
```
to

def main():
    for target in ['zenith', 'azimuth']:
        pulsemap = 'TWSRTHVInIcePulsesIC'
        nb_neighbours = x
```

where x is a variable.

2. Run the modified training script for zenith and azimuthal regression for `nb_neighbours = [4, 16]`. Consult logs to see if the training converged within the specified number of epochs.

**Benchmark deliverance**
Reply to this issue with two plots and attach the modified training script and other relevant changes. Each plot is a `matplotlib.pyplot.subplots` figure, where the upper plot shows resolution, and the bottom plot shows the relative improvement. See attached example.

1. zenith resolution vs. true energy with curves from `dynedge baseline` and `dynedge with k = x. Plot has relative improvement shown in the bottom.
2. azimuth resolution vs. true energy with curves from `dynedge baseline` and `dynedge with k = x`. Plot has relative improvement shown in the bottom.

 Relative improvement of the modification w.r.t. the baseline is given by (`relative improvement = (1 - resolution_modification/resolution_baseline)*100`). 



Example Figure

![billede](https://user-images.githubusercontent.com/48880272/197970973-7a67c472-81bb-4780-8bb6-4746902c51d3.png)

**Comment by Andreas-MJ** [comment]
Apart from changing nb_neighbours to x in main(), I change nb_nearest_neighbours to x in graph_builder() as well.

**Comment by Andreas-MJ** [comment]
![northern_tracksZenith_resolution_new_dynedge](https://user-images.githubusercontent.com/72250101/203010863-c54cc9ab-4803-453d-b815-aa3cf26cf474.png)
![northern_tracksAzimuth_resolution_new_dynedge](https://user-images.githubusercontent.com/72250101/203010949-7c04e54f-453d-4ce1-a676-1da9dfc652ac.png)
