### ISSUE TITLE
SQLite chunking and datastreaming

### ISSUE THREAD

**Issue by MortenHolmRep** [graphnet-team/graphnet#330]
**Is your feature request related to a problem? Please describe.**
With very large datasets, loading the dataset become an issue as memory usage increases and in the end makes it such that the dataset cannot be loaded.
Besides the memory issue, script performance also drastically drops when we have to load such large datasets.

**Describe the solution you'd like**
SQLite features data chunking (batching) and datastreaming, where only the relevant data is called when used.
An implementation would look like [this solution](https://pythonspeed.com/articles/pandas-sql-chunking/)

**Comment by MortenHolmRep** [comment]
While I guess chunking and streaming can be used for plotting, this is not intended for plotting. 
It is for the legacy implementation of SQL reading currently done in GraphNet for use in GraphNet, not analysis.
I assume it can be done for both SQL and parquet, especially following the two other examples provided later of a PyTorch streaming dataloader.

From the examples; [chunking and streaming SQLite](https://pythonspeed.com/articles/pandas-sql-chunking/) or [Streaming DataLoader with PyTorch example 1](https://medium.com/speechmatics/how-to-build-a-streaming-dataloader-with-pytorch-a66dd891d9dd) or [Streaming DataLoader with PyTorch example 2](https://visualstudiomagazine.com/Articles/2021/04/01/pytorch-streaming.aspx?Page=1) you can iterate on a dataset instead of loading the entire set.

In essence, the streaming and chunking are just taking a large dataset and splitting it down into batch-sized components, but at the earliest stage in the process, when loading the data for each individual worker.

**Comment by RasmusOrsoe** [comment]
We already have this feature for the training / prediction. If you compare in detail the guides you link here and our Dataset class. You never have more than `batch_size * (1 + prefetch_factor)` in memory when training / predicting. 

I'm closing the issue because of redundancy. If I misunderstand you, please feel free to reopen the issue.
