### ISSUE TITLE
Ordering of Table names is not fixed ->  SQLiteConverter.merge fails

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#336]
**Describe the bug**

To my surprise,  SQLiteConverter does not neccesarily write i3 files to sqlite databases with the same table order. 

e.g. database1 could have `tables = [table1, table2, table3]` but database2 could have `tables=[table2, table1, table3]`. See attached picture for a real-life example on new upgrade MC.

![image](https://user-images.githubusercontent.com/48880272/199476743-c6c19b99-16c7-46ea-a803-d3b8e96b4cc3.png)

The i3 files are located at `/home/rorsoe/phd/upgrade/test_data`

This is an issue, because when you call SQLiteConverter.merge(), the `_extract_table_names` contains an assert statement
`assert all([results[0] == r for r in results])` that fails if the tables are ordered differently.

I have not yet figured out _why_ the ordering is different. I'm not sure if the bug is which of the following

1. Differently ordered tables
2. assert statement assumes same ordering

but it's my impression that differently ordered tables shouldn't matter for the merging, as each table is read out separately before submitted to the merged database. So I think this can be solved by just changing the assert statement to 
`assert all([results[0].sorted() == r.sorted() for r in results])`

**To Reproduce**
1. Download the files: `/home/rorsoe/phd/upgrade/test_data` 
2. Run this

```

import logging
import os

from graphnet.utilities.logging import get_logger

from graphnet.data.extractors import (
    I3FeatureExtractorIceCubeUpgrade,
    I3TruthExtractor,
    I3GenericExtractor,
    I3PulseNoiseTruthFlagIceCubeUpgrade,
)

from graphnet.data.sqlite import SQLiteDataConverter

logger = get_logger(level=logging.INFO)

CONVERTER_CLASS = {
    "sqlite": SQLiteDataConverter,
    "parquet": ParquetDataConverter,
}


def main_icecube_upgrade(backend: str):
    """Convert IceCube-Upgrade I3 files to intermediate `backend` format."""
    # Check(s)
    assert backend in CONVERTER_CLASS
    database_name = 'dev_step4_upgrade_0028_numu_nutau_01.11.202_test_debug_v2'
    inputs = ["/home/rorsoe/phd/upgrade/test_data"]
    outdir = f"debug_test/{database_name}"
    workers = 3
    converter = CONVERTER_CLASS[backend](
        [
            I3TruthExtractor(),
          I3FeatureExtractorIceCubeUpgrade(
                "SplitInIcePulses"
            ),
          I3PulseNoiseTruthFlagIceCubeUpgrade(
                "SplitInIcePulses_TruthFlags"
            ),
            I3FeatureExtractorIceCubeUpgrade(
              "SplitIceCubePulsesTWSRT"
            ),
          I3PulseNoiseTruthFlagIceCubeUpgrade(
               "SplitIceCubePulsesTWSRT_TruthFlags"
           ),
          I3FeatureExtractorIceCubeUpgrade(
             "SplitInIcePulses_GraphSage_Pulses"
           ),
          I3PulseNoiseTruthFlagIceCubeUpgrade(
               "SplitInIcePulses_GraphSage_Predictions"
            ),
        ],
        outdir + '/tmp',
        workers=workers,
        icetray_verbose=1,
        gcd_rescue = '/data/sim/IceCubeUpgrade/genie/step4/140028/GeoCalibDetectorStatus_ICUpgrade.v58.mixed.V0.i3.bz2'
    )
    os.makedirs(outdir + '/data/')
    converter(inputs)
    if backend == "sqlite":
        converter.merge_files(outdir + '/data/' + database_name)


if __name__ == "__main__":
    backend = "sqlite"
    main_icecube_upgrade(backend)
```

**Expected behavior**
Script should run without error

**Full traceback**
Please include the full error message to allow for debugging
```
Traceback (most recent call last):
  File "make_database.py", line 73, in <module>
    main_icecube_upgrade(backend)
  File "make_database.py", line 68, in main_icecube_upgrade
    converter.merge_files(outdir + '/data/' + database_name)
  File "/home/rorsoe/software/graphnet/src/graphnet/data/sqlite/sqlite_dataconverter.py", line 77, in merge_files
    table_names = self._extract_table_names(input_files)
  File "/home/rorsoe/software/graphnet/src/graphnet/data/sqlite/sqlite_dataconverter.py", line 102, in _extract_table_names
    assert all([results[0] == r for r in results])
AssertionError
```

**Additional context**
I think the different ordering could be triggered by empty extractions. But I know that the files mentioned here has empty pulsemaps for only some events; so the none of the tables should be empty for an entire file.

**Comment by RasmusOrsoe** [comment]
@asogaard Let me know what you think. For now, I'll go with the `.sorted()` solution.

**Comment by asogaard** [comment]
Yeah, that's a bit weird. From [here](https://github.com/graphnet-team/graphnet/blob/main/src/graphnet/data/dataconverter.py#L164), [here](https://github.com/graphnet-team/graphnet/blob/main/src/graphnet/data/dataconverter.py#L415), and [here](https://github.com/graphnet-team/graphnet/blob/main/src/graphnet/data/sqlite/sqlite_dataconverter.py#L30-L50) it should seem like the tables should have a fixed order.

For my understanding: In the code to reproduce, I don't see how the keys `pisa_dependencies` and `SplitIceCubePulsesTWSRT` in the screenshot make it into the databases. Could you describe that?

**Comment by RasmusOrsoe** [comment]
Hey @asogaard  thanks for the reply. `pisa_dependencies`  is the table name from #339 which i used locally, but removed from the MWE - sorry for the confusion.

All other tables should be there, including `SplitIceCubePulsesTWSRT`
