### ISSUE TITLE
Setup tests of data extraction for PR's to ensure no surprises later on

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#338]
**Is your feature request related to a problem? Please describe.**
As documented in #337  and #336 and older issues, our PR tests does not sufficiently test that changes to the code base doesn't break data extraction functionality. I think we **need** to set this up asap to avoid these surprises. 

**Describe the solution you'd like**
I would like for every PR (maybe just PR's that has changes to data extraction code) to be vetted thoroughly with unit tests before merged to main. I propose that

1. I find the suitable data and make it publicly available
2. I will write the tests that I find necessary
3. @asogaard  adds this to PR checks 

@asogaard  what do you say?

**Describe alternatives you've considered**
Jumping out the window

**Comment by RasmusOrsoe** [comment]
Cool. I will provide you with i3 files that we can put directly in the repo for conversion by the end of next week.

**Comment by asogaard** [comment]
I will close this, as #290 is not solved and as the additional tests suggested here fall under #102 — I suggest I continue any discussion there!
