### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#369]
**Describe the bug**
an error related to pydantic makes the import statement

`from graphnet.deployment.i3modules import GraphNeTModuleIceCubeUpgrade `

fail.

**To Reproduce**
1. Open your favorite cvfms
2. install graphnet via the cvmfs installation instructions
3. run the import statement `from graphnet.deployment.i3modules import GraphNeTModuleIceCubeUpgrade`

**Expected behavior**
Import should not fail.

**Full traceback**
Please include the full error message to allow for debugging
```
graphnet: INFO     2022-12-07 04:50:38 - get_logger - Writing log to logs/graphnet_20221207-045038.log
Traceback (most recent call last):
  File "inference_test.py", line 13, in <module>
    from graphnet.deployment.i3modules import GraphNeTModuleIceCubeUpgrade #PulseCleaner
  File "/home/rorsoe/software/graphnet/src/graphnet/deployment/i3modules/__init__.py", line 8, in <module>
    from .graphnet_module import *
  File "/home/rorsoe/software/graphnet/src/graphnet/deployment/i3modules/graphnet_module.py", line 16, in <module>
    from graphnet.models import StandardModel
  File "/home/rorsoe/software/graphnet/src/graphnet/models/__init__.py", line 11, in <module>
    from .model import Model
  File "/home/rorsoe/software/graphnet/src/graphnet/models/model.py", line 16, in <module>
    from graphnet.utilities.config import Configurable, ModelConfig
  File "/home/rorsoe/software/graphnet/src/graphnet/utilities/config/__init__.py", line 3, in <module>
    from .configurable import Configurable
  File "/home/rorsoe/software/graphnet/src/graphnet/utilities/config/configurable.py", line 6, in <module>
    from graphnet.utilities.config.base_config import BaseConfig
  File "/home/rorsoe/software/graphnet/src/graphnet/utilities/config/base_config.py", line 8, in <module>
    from pydantic import BaseModel
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
    """This directory is meant for IPython extensions."""
  File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
    #   |
ImportError: cannot import name dataclass_transform
```

**Additional context**
Could we make a cvmfs build test for PR's also? Would be nice to avoid these surprises..

**Comment by asogaard** [comment]
I think this is specific to the Upgrade version of CVMFS you're using. (I saw the same thing yesterday, but not in my normal setup.)

**Comment by RasmusOrsoe** [comment]
@asogaard do you have any pointers on how to fix this? Is it on my end?

**Comment by asogaard** [comment]
I suspect it has to do with conflicting `pydantic` versions in the specific CVMFS version we're using for Upgrade. Don't have any specific points at this moment, but will try to look into it.

**Comment by RasmusOrsoe** [comment]
Sounds great! It's a real road block right now..

**Comment by asogaard** [comment]
Alright, the issue seems to be related to the version of `typing_extensions`, see [here](https://github.com/ray-project/ray/issues/31227). Using this CVMFS setup:
```bash
eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/setup.sh`
/cvmfs/icecube.opensciencegrid.org/users/upgrade-sim/software/icetray/branches/icecube_upgrade/build__py3-v4.1.1__osgvo-el7/env-shell.sh
```
loads an environement that comes with `typing_extensions=4.0.1` installed.

The following two steps remove the error for me:

1. Updating `$ pip install --upgrade [--user] typing_extensions>=4.4.0`
2. Make sure that my local pip packages are loaded using `export PYTHONPATH=~/.local/lib/python3.7/site-packages/:$PYTHONPATH`. For some reason that didn't work. If this is a recurring problem for you as well, consider putting this in you `.bashrc` script or in your CVMFS initialisation script (if you have one).

Let me know if this does the job, @RasmusOrsoe.

**Comment by OmriTreidel** [comment]
@asogaard the latest version of `typing_extensions` is 4.4.0 https://pypi.org/project/typing-extensions/. What version do you end up with ?

**Comment by RasmusOrsoe** [comment]
@asogaard I can confirm that the fix works. That was a huge help! @OmriTreidel this cvmfs came with `typing_extensions=4.0.1`.
