### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by JostMigenda** [graphnet-team/graphnet#397]
As part of openjournals/joss-reviews#4971, I’ve tried to run the Docker image and have a couple of initial notes/issues. (This is just a quick list based on initial impressions; I didn’t want to open lots of small issues immediately, but please feel free to move individual points into their own issue if you think it’s appropriate.)

- [x] The total download size was ~10 GB, which was larger than I expected. I feel like that’s large enough that a warning in the README file might be appropriate.
- [x] Additionally, the README file recommends `docker run --rm […]`, which according to documentation automatically removes the Docker container after it exits. Does that mean I would have to re-download the whole ~10 GB every single time? (I vaguely remember that Docker lets you update layers of a container without having to rebuild lower layers—so e.g. updating from graphnet v0.2.3 to v0.2.4 would only require downloading and rebuilding the graphnet part, but not other parts of the container (Linux, Python, PyTorch, …); that would probably be very useful here.)
- [x] The container downloaded by `asogaard/graphnet:latest` is v0.2.3; [there is no container for v0.2.4](https://hub.docker.com/r/asogaard/graphnet/tags) (which was tagged 11 hours ago) and the GitHub Action that automatically builds & uploads containers [appears to be broken](https://github.com/graphnet-team/graphnet/actions/runs/4014734888) currently.
- [x] Once the container is built, instead of `~/graphnet` (as in the README) I find myself in `~` and there is no `graphnet` directory. (GraphNeT itself is installed in `/usr/local/lib/python3.8/dist-packages/graphnet/`; but of course that doesn’t include the examples directory.) Instead, there are only:
```bash
root@c77c9a429624:~# ls
cppzmq-master/  master.tar.gz  photospline-2.0.7/
```

**Comment by asogaard** [comment]
Aye, this is known, cf. [here](https://github.com/graphnet-team/graphnet/actions/workflows/docker.yml) where the build producing the image failed from v0.2.4 onwards. But working on it over [here](https://github.com/asogaard/graphnet/tree/update-docker), addressing all four issues above, and will create a PR soon. :)

**Comment by asogaard** [comment]
Alright, following the merge of #399 we have a new `main` docker image [here](https://hub.docker.com/layers/asogaard/graphnet/main/images/sha256-cf49a193a0aaee5eb2636e483dfad1c391fe735291d4132e164a96349b35d0d1?context=repo):

* It's 1.59 GB in size cf. approx. 10 GB before. This is down to the base [icetray image](https://hub.docker.com/r/icecube/icetray) used, where we have switched from `combo-stable` to `combo-stable-slim`.
* Using the `--rm` option with `docker run` doesn't remove the downloaded _image_, just the running _container_ and it's filesystem. (The idea is that if you do `docker run` many times without `--rm?  , you create lots of persistent containers that quickly clutter a lot). So you shouldn't have to redownload the _X_ GBs with every run. But I can try to make clear in the instructions that this is entirely optional — and that in some cases you might want to keep the container after exiting.
* Yeah, `v0.2.4` broke. The `asogaard/graphnet:main` container now works as intended. Once you all have had a chance to check that it looks fine, I'll create another tag (`v0.2.5`) such that the `latest` tag will also be the updated version.
* The file system should look as indicated in the README.

So make sure that you pull the `main` version from Dockerhub, and let me know if you consider the four tasks above resolved. (I'll leave it to you to check them off.)

**Comment by JostMigenda** [comment]
I’ve just tested `asogaard/graphnet:main` and it looks good now. Thanks also for clearing up my misunderstanding of `--rm`!
