### ISSUE TITLE
Make PISA examples self-contained

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#404]
**Is your feature request related to a problem? Please describe.**
With #378 most examples scripts are self-contained, i.e. referring only to files that come bundled with the repo. The only exception is the PISA ones.

**Describe the solution you'd like**
It would be nice if all the example scripts we provide, including the PISA ones, could be run out of the box, provided of course that the necessary packages are installed. This is also requested here: https://github.com/openjournals/joss-reviews/issues/4971#issuecomment-1408985970.

**Describe alternatives you've considered**
If we want to keep our examples self-contained, the alternative would be to not provide examples on the interface with PISA, but I think this would be a shame.

**Comment by RasmusOrsoe** [comment]
@asogaard as discussed with you and @philippeller , we cannot do this unless we have significantly higher statistics in our public data. (Running a minimizer on ~5 events wont work). So I think we can close this.

**Comment by asogaard** [comment]
Closing in favour of #428
