### ISSUE TITLE
Install PISA in main Docker image

### ISSUE THREAD

**Issue by asogaard** [graphnet-team/graphnet#405]
**Is your feature request related to a problem? Please describe.**
Right now the main `graphnet` docker image comes with `graphnet` and `icetray` installed, which allows for running most example scripts out of the box. However, currently PISA is not installed, which means that the PISA examples scripts (even if they were self-contained; cf. #404) cannot be run out of the box in the provided Docker image, which can be frustrating. See also https://github.com/openjournals/joss-reviews/issues/4971#issuecomment-1408985970.

**Describe the solution you'd like**
It would be nice to provide a Docker image that comes with all the most relevant packages installed, including ancillary ones like PISA.

**Describe alternatives you've considered**
Alternatively, we should decide that it is not within the scope of `graphnet` proper to support an interface with PISA (arguing, e.g., that it is a very specialised end-use case) and move this functionality out of the main repository. Tagging @RasmusOrsoe for a second opinion.

**Comment by JostMigenda** [comment]
FWIW, if you decide that PISA support is a specialized, IceCube-proprietary feature and not intended for general usage, then I think it's sufficient if you explicitly state that in the module docstring and the examples/04_pisa README.
Please don't feel like you have to remove the code and put it e.g. in a separate repo which might make it harder to use.
