### ISSUE TITLE
Running 02_plot_feature_distributions.py on the oscNext_genie_level7_v02 dataset 

### ISSUE THREAD

**Issue by AishwaryaUMD** [graphnet-team/graphnet#423]
Description
The sqlite file produced when 01_convert_i3_files.py is run on the example test dataset oscNext_genie_level7_v02 produced an output file oscNext_genie_level7_v02_first_5_frames.db. When this file was run with 02_plot_feature_distributions.py, an error was obtained. 

Reproducing Error 
Path to 01_convert_i3_files.py (a)
/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/examples/01_icetray/01_convert_i3_files.py

Path to oscNext_genie_level7_v02 (b)
/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/data/tests/i3/oscNext_genie_level7_v02

Run the i3 convertor (a) with the test dataset (b) to produce oscNext_genie_level7_v02_first_5_frames.db in the graphnet/data/examples/outputs/convert_i3_files/ic86 folder. Run this file with the 02_plot_feature_distributions.py file to reproduce error. 

Path to 02_plot_feature_distributions.py 
/data/condor_builds/users/avijai/IceCube/for_nn/graphnet/examples/02_data/02_plot_feature_distributions.py

Path to .yml file used in 02_plot_feature_distributions.py
/data/condor_builds/users/avijai/IceCube/for_nn/graphnet/configs/datasets/test_data_sqlite.yml

Error Message 
graphnet: INFO     2023-02-06 11:08:20 - get_logger - Writing log to logs/graphnet_20230206-110820.log
graphnet: WARNING  2023-02-06 11:08:24 - warn_once - `icecube` not available. Some functionality may be missing.
graphnet: WARNING  2023-02-06 11:08:24 - SQLiteDataset.warning - Removing the following (missing) features: dom_z, pmt_area, rde, dom_y, dom_x, dom_time
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "02_plot_feature_distributions.py", line 94, in <module>
    main()
  File "02_plot_feature_distributions.py", line 35, in main
    x_preprocessed_list.append(detector(batch).x.numpy())
  File "/data/condor_builds/users/avijai/IceCube/for_nn/miniconda/envs/graphnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/condor_builds/users/avijai/IceCube/for_nn/graphnet/src/graphnet/models/detector/detector.py", line 47, in forward
    assert data.x.size()[1] == self.nb_inputs, (
AssertionError: ('Got graph data with incompatible size, ', 'torch.Size([9, 1]) vs. 7 expected')

Additional context
I think the problem may be arising due to the number of missing features dom_z, pmt_area, rde, dom_y, dom_x, dom_time)  in this dataset that have to be removed, a total of 6 which is causing the graph data to be of an incompatible size (1 as opposed to 7). This indicates that perhaps feature extraction is casing on a different naming system for the features that need to be extracted or is expecting features that aren't available in all datasets.

**Comment by MortenHolmRep** [comment]
I have tried replicating your steps
1. entered Icetray
2. activated graphnet environment
3. ran default `01_convert_i3_files.py` script via `python 01_convert_i3_files.py sqlite icecube-86`. An output folder was generated at `../graphnet/data/examples/output/convert_i3_files/ic86/` containing the database `oscNext_genie_level7_v02_first_5_frames`.
4. ran default `02_plot_feature_distributions.py` script via `python 02_plot_feature_distributions.py,` which did not generate an output plot, but did run without errors.
5. I changed the output directory of the plotting routines and generated two plots.

@AishwaryaUMD It does look like the features for the database you generated need to be corrected. Can you instead delete the database you generated and try again following my steps?

**Comment by AishwaryaUMD** [comment]
Hi @MortenHolmRep! I replicated your steps but when you reach step 4, the 02_plot_feature_distributions.py file uses the oscNext_genie_level7_v02_first_5_frames.db by default, found at this path $GRAPHNET/data/tests/sqlite/oscNext_genie_level7_v02/oscNext_genie_level7_v02_first_5_frames.db as seen in the test_data_sqlite.yml file found at this path /graphnet/configs/datasets/test_data_sqlite.yml. This does generate the necessary plots. However, when updating the path in test_data_sqlite.yml to the file generated by 01_convert_i3_files.py, found at ../graphnet/data/examples/output/convert_i3_files/ic86/, the above error is seen. I hope that clarifies the issue I'm having.

**Comment by MortenHolmRep** [comment]
Thank you for the clarification :)
The error comes down to how the two databases were extracted; therefore, they are not directly comparable; one was likely extracted using the generic extractor and the other using the feature extractor. Extracting with the generic extractor pulls out all information, while the feature extractor pulls out needed information and converts the naming convention. It also means the two methods are not directly comparable as a variable like dom_x with feature extractor is likely called position__x with generic extractor.
It is something we need to look into, given time.

Here is some step you can take to ensure the correct format of the database features for future troubleshooting.
In the file `../graphnet/configs/datasets/test_data_sqlite.yml`, we have the specified features and truth variables that we look for in out databases.
```
features:
  - dom_x
  - dom_y
  - dom_z
  - dom_time
  - charge
  - rde
  - pmt_area
truth:
  - energy
  - position_x
  - position_y
  - position_z
  - azimuth
  - zenith
  - pid
  - elasticity
  - sim_type
  - interaction_type
```

Upon inspecting the two databases

1. `sqlite3 <path/to/database.db>`
2. `.table` (gives a list of tables in the database)
3. `.schema <relevant table>`

We have the following tables (for this context, with unused features removed)
`../graphnet/data/examples/output/convert_i3_files/ic86/oscNext_genie_level7_v02_first_5_frames.db`
Truth:
```sqlite
azimuth FLOAT, elasticity FLOAT, energy FLOAT, interaction_type FLOAT, pid FLOAT, position_x FLOAT, position_y FLOAT, position_z FLOAT, sim_type FLOAT, zenith FLOAT;
```
Features:
```
area FLOAT, charge FLOAT, direction__azimuth FLOAT, direction__zenith FLOAT, position__x FLOAT, position__y FLOAT, position__z FLOAT, relative_dom_eff FLOAT
```
In the table, for features, we see `position__x`, and you could try to alter the features in the .yml file from, e.g. `dom_x` to `position__x`. I have yet to try it, though.

and
`../graphnet/data/tests/sqlite/oscNext_genie_level7_v02/oscNext_genie_level7_v02_first_5_frames.db`
Truth:
```sqlite
azimuth FLOAT, elasticity FLOAT, energy FLOAT, interaction_type FLOAT, pid BIGINT, position_x FLOAT, position_y FLOAT, position_z FLOAT, sim_type TEXT, zenith FLOAT
```
Features:
```
charge FLOAT, dom_time FLOAT, dom_x FLOAT, dom_y FLOAT, dom_z FLOAT, pmt_area FLOAT, rde FLOAT
```

I hope it helps!

I am closing this issue; feel free to reopen it if you do not feel this answers your question :)
