### ISSUE TITLE
Skipping the Nullsplit P-frames in the Snowstorm data doesn't seem to fix the problem

### ISSUE THREAD

**Issue by Andreas-MJ** [graphnet-team/graphnet#433]
I just made a pull request #432 of the updated dataconverter.py and expected my version of 01_convert_i3_files.py to run. However, I got the following error message:

nohup: ignoring input

  0%|[32m          [0m| 0/1623 [00:00<?, ?file(s)/s]
  2%|[32m▏         [0m| 37/1623 [00:00<00:31, 49.99file(s)/s]
  3%|[32m▎         [0m| 42/1623 [00:07<05:57,  4.42file(s)/s]
  3%|[32m▎         [0m| 45/1623 [00:07<06:02,  4.35file(s)/s]
  3%|[32m▎         [0m| 47/1623 [00:09<07:49,  3.36file(s)/s]
  3%|[32m▎         [0m| 49/1623 [00:10<08:06,  3.23file(s)/s]
  3%|[32m▎         [0m| 50/1623 [00:11<08:32,  3.07file(s)/s]
  3%|[32m▎         [0m| 51/1623 [00:11<09:10,  2.86file(s)/s]
  3%|[32m▎         [0m| 52/1623 [00:13<16:00,  1.64file(s)/s]
  3%|[32m▎         [0m| 53/1623 [00:16<23:06,  1.13file(s)/s]
  3%|[32m▎         [0m| 54/1623 [00:16<22:17,  1.17file(s)/s]
  3%|[32m▎         [0m| 55/1623 [00:18<23:35,  1.11file(s)/s]
  3%|[32m▎         [0m| 56/1623 [00:20<32:05,  1.23s/file(s)]
  4%|[32m▎         [0m| 57/1623 [00:20<27:29,  1.05s/file(s)]
  4%|[32m▎         [0m| 58/1623 [00:23<39:11,  1.50s/file(s)]
  4%|[32m▎         [0m| 59/1623 [00:24<34:17,  1.32s/file(s)]
  4%|[32m▎         [0m| 60/1623 [00:24<27:37,  1.06s/file(s)]
  4%|[32m▍         [0m| 62/1623 [00:25<20:06,  1.29file(s)/s]
  4%|[32m▍         [0m| 63/1623 [00:26<17:41,  1.47file(s)/s]
  4%|[32m▍         [0m| 64/1623 [00:26<15:09,  1.71file(s)/s]
  4%|[32m▍         [0m| 65/1623 [00:27<19:31,  1.33file(s)/s]
  4%|[32m▍         [0m| 66/1623 [00:28<19:18,  1.34file(s)/s]
  4%|[32m▍         [0m| 67/1623 [00:30<26:39,  1.03s/file(s)]
  4%|[32m▍         [0m| 68/1623 [00:33<46:15,  1.78s/file(s)]
  4%|[32m▍         [0m| 70/1623 [00:36<42:52,  1.66s/file(s)]
  4%|[32m▍         [0m| 71/1623 [00:38<44:02,  1.70s/file(s)]
  4%|[32m▍         [0m| 72/1623 [00:39<38:54,  1.51s/file(s)]
  4%|[32m▍         [0m| 73/1623 [00:39<30:03,  1.16s/file(s)]
  5%|[32m▍         [0m| 74/1623 [00:41<34:35,  1.34s/file(s)]
  5%|[32m▍         [0m| 75/1623 [00:41<26:02,  1.01s/file(s)]
  5%|[32m▍         [0m| 76/1623 [00:42<25:00,  1.03file(s)/s]
  5%|[32m▍         [0m| 77/1623 [00:43<23:51,  1.08file(s)/s]
  5%|[32m▍         [0m| 78/1623 [00:45<30:35,  1.19s/file(s)]
  5%|[32m▍         [0m| 79/1623 [00:45<24:41,  1.04file(s)/s]
  5%|[32m▍         [0m| 81/1623 [00:46<17:59,  1.43file(s)/s]
  5%|[32m▌         [0m| 82/1623 [00:47<23:31,  1.09file(s)/s]
  5%|[32m▌         [0m| 83/1623 [00:48<21:14,  1.21file(s)/s]
  5%|[32m▌         [0m| 84/1623 [00:48<17:00,  1.51file(s)/s]
  5%|[32m▌         [0m| 86/1623 [00:49<14:08,  1.81file(s)/s]
  5%|[32m▌         [0m| 87/1623 [00:52<27:27,  1.07s/file(s)]
  5%|[32m▌         [0m| 88/1623 [00:52<24:46,  1.03file(s)/s]
  5%|[32m▌         [0m| 89/1623 [00:54<28:01,  1.10s/file(s)]
  6%|[32m▌         [0m| 90/1623 [00:54<22:09,  1.15file(s)/s]
  6%|[32m▌         [0m| 91/1623 [00:56<26:52,  1.05s/file(s)]
  6%|[32m▌         [0m| 93/1623 [00:57<21:27,  1.19file(s)/s]
  6%|[32m▌         [0m| 94/1623 [00:58<24:37,  1.03file(s)/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/lustre/hpc/icecube/andreasmj/work/graphnet/src/graphnet/data/dataconverter.py", line 83, in wrapper
    output_file = process_method(self, *args)
  File "/lustre/hpc/icecube/andreasmj/work/graphnet/src/graphnet/data/dataconverter.py", line 381, in _process_file
    self.save_data(data, output_file)
  File "/lustre/hpc/icecube/andreasmj/work/graphnet/src/graphnet/data/sqlite/sqlite_dataconverter.py", line 35, in save_data
    assert len(data)
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "convert_i3_files_feature.py", line 70, in <module>
    main_icecube86(backend)
  File "convert_i3_files_feature.py", line 61, in main_icecube86
    converter(inputs)
  File "/lustre/hpc/icecube/andreasmj/work/graphnet/src/graphnet/data/dataconverter.py", line 215, in __call__
    self.execute(filesets)
  File "/lustre/hpc/icecube/andreasmj/work/graphnet/src/graphnet/data/dataconverter.py", line 286, in execute
    pool = self._iterate_over_individual_files(filesets)
  File "/lustre/hpc/icecube/andreasmj/work/graphnet/src/graphnet/data/dataconverter.py", line 331, in _iterate_over_individual_files
    self._process_file, tqdm(args, unit="file(s)", colour="green")
  File "/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/python3.7/multiprocessing/pool.py", line 748, in next

  6%|[32m▌         [0m| 95/1623 [00:58<19:03,  1.34file(s)/s]    raise value
AssertionError

  6%|[32m▌         [0m| 96/1623 [00:58<15:36,  1.63file(s)/s]

```

**Comment by MortenHolmRep** [comment]
The first traceback is related to the assertion that len(data) > 0.
Could you check that you do not have empty files or pulses?
You can check if you have empty files by running `ls -lh` in your directory and examining the files.

**Comment by asogaard** [comment]
What @MortenHolmRep says. ☝️  

The fact that it comes at step 94 of 1623 suggests its a problem with the input file(s). Make sure that you understand why you might have empty I3-files, if you have any. Then try using a batching strategy such that you group e.g. 100 I3-files into a single database (see some suggestions [here](https://github.com/graphnet-team/graphnet/blob/main/examples/01_icetray/01_convert_i3_files.py#L71-L73) and in the documentation for [DataConverter](https://github.com/graphnet-team/graphnet/blob/81fce2e7d9558ddabcea732fa5fb05837cd4c60c/src/graphnet/data/dataconverter.py#L111-L140)).

**Comment by Aske-Rosted** [comment]
I have found scenarios in which you would come to have empty pulse-maps even with the current skipping of NullSplit frames...
If there are two subevents in one event both might be recorded in the I3 file with subevent 0 and subevent = 1, however both of these subevents will not necessarily have the expected pulsemap, even worse is it that the "correct" subevent will be in subevent 0 or subevent 1, so the event header cannot be used to filter out the "incorrect" subevent like with the NullSplit check.  

I do not know if this is the intended data structure or if this is a bug in the production of the data files.

I cannot find a solution to this other than checking if desired pulse-map exists in frame and skipping entire frame if it does not.

![double_non_NullSplit_frame_incorrect](https://user-images.githubusercontent.com/111734311/220517524-fb88e4a5-165f-4b3a-8f97-579ae4a5baac.png)
![event_header_correct](https://user-images.githubusercontent.com/111734311/220517534-12c60337-1c96-4db1-9d96-d6d647c4bd29.png)
![event_header_incorrect](https://user-images.githubusercontent.com/111734311/220517537-8cfcbed1-cabd-469a-97d2-c3c801aa604b.png)
![double_non_NullSplit_frame_correct_frame](https://user-images.githubusercontent.com/111734311/220517541-3cd78b37-09a4-40f9-ac6a-677cc6851743.png)

**Comment by MortenHolmRep** [comment]
@Aske-Rosted Nicely spotted! This would be a good issue to bring up on one of the IceCube slack channels, I imagine @software would be the place. It could give us clues as to how to proceed.

**Comment by asogaard** [comment]
Hi @Andreas-MJ, @Aske-Rosted and @MortenHolmRep,

I'll be closing this issue because it is rather broad and seems like a data problem (see [above](https://github.com/graphnet-team/graphnet/issues/433#issuecomment-1433425760)). At least, we don't know if this is a `graphnet` bug or something else, and until then I figure using the #help channel in Slack is the best place to get feedback. Let me know if you disagree, @Andreas-MJ. Once the problem has been narrowed down, I encourage you to open a more specific issue. 

Similarly, @Aske-Rosted's observation is interesting (I suspect it is the result of event splitting), but since it is not clear that this has a bearing on @Andreas-MJ's initial problem, I think you should open a separate, focused issue for this, if necessary.
