### ISSUE TITLE
name 'torch' is not defined when using pickled Model with _transform_prediction set.

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#447]
**Describe the bug**
When we set `_transform_prediction = torch.log10` and save the model to `.pth`, that same model will produce a module error when loaded into memory again and evaluated on new data.

**To Reproduce**
1. Run training example (as-is) `02_train_model_without_configs.py`
2. When the model is saved to disk, try to load it into memory in a separate script using

path_to_model = 'my_path/model.pth'
model = torch.load(path_to_model, map_location = 'cpu', pickle_module = dill)

3. Evaluate the model on any of public events using `results = model(batch)`
See error

**Expected behavior**
We should be able to pickle and re-load any model and reapply them without this error. 

**Full traceback**
Please include the full error message to allow for debugging
```
file "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/iwsatlas1/oersoe/github/graphnet/src/graphnet/models/standard_model.py", line 93, in forward
    preds = [task(x) for task in self._tasks]
  File "/home/iwsatlas1/oersoe/github/graphnet/src/graphnet/models/standard_model.py", line 93, in <listcomp>
    preds = [task(x) for task in self._tasks]
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/iwsatlas1/oersoe/github/graphnet/src/graphnet/models/task/task.py", line 114, in forward
    return self._transform_prediction(x)
  File "/home/iwsatlas1/oersoe/github/graphnet/src/graphnet/models/task/task.py", line 123, in _transform_prediction
    return self._transform_prediction_training(prediction)
  File "<string>", line 1, in <lambda>
NameError: name 'torch' is not defined
```

**Additional context**

**Comment by asogaard** [comment]
I don't seem to be able to reproduce this error. Working off `main`, I first run
```bash
$ python examples/04_training/02_train_model_without_configs.py --max-epochs 1
```
This yields the model `.pth` file `(...)/examples/output/train_model_without_configs/prometheus-events/dynedge_total_energy_example/model.pth`.

When I then run the following script
```python
from graphnet.constants import CONFIG_DIR
from graphnet.data.dataloader import DataLoader
from graphnet.models import Model
from graphnet.utilities.config import DatasetConfig

# Load model
path_to_model = "(...)/examples/output/train_model_without_configs/prometheus-events/dynedge_total_energy_example/model.pth"
model = Model.load(path_to_model)  # Equivalent: torch.load(path_to_model, map_location="cpu", pickle_module=dill)
model.train()  # Also tried: model.inference()

# Load data
dataset_config_path = f"{CONFIG_DIR}/datasets/training_example_data_sqlite.yml"
dataset_config = DatasetConfig.load(dataset_config_path)
dataloaders = DataLoader.from_dataset_config(
    dataset_config,
    batch_size=16,
    num_workers=10,
)

# Run inference
batch = next(iter(dataloaders["train"]))
preds = model(batch)

print(preds)
```
I get expected results:
```
[tensor([[1.1559],
        (...)
        [1.1602]], grad_fn=<Log10Backward0>)]
```
The `grad_fn` tells me that `torch.log10` is being applied. Results are also OK when using `model.inference()` which would mean that `torch.log10` were not applied.

@RasmusOrsoe let me know if you have done something else to see the able behaviour.

**Comment by RasmusOrsoe** [comment]
@asogaard updated my branch to main and can confirm its gone!
