### ISSUE TITLE
Add checks for primary key and index in truth and pulsemap table 

### ISSUE THREAD

**Issue by MoustHolmes** [graphnet-team/graphnet#450]
I made a bug report last week about a run with bad GPU performance ( #440 ). The problem was that the dataset had been modified and in the process lost its primary key on event_no in the truth table meaning that instead of doing a search of event_no sqlite were doing a much more computational heavy scan instead.

I suggest adding a check for whether event_no is a index in pulsemap table and a primary key in the truth table. Since modifying the database after its creation might be something someone would like to do and running with the wrong schema is a very subtle bug that is hard to diagnose for someone without knowledge about SQLite.

**Comment by RasmusOrsoe** [comment]
@MoustHolmes We have checks in the conversion code for this. Could you please elaborate on how the database lost its primary key?

**Comment by MoustHolmes** [comment]
@RasmusOrsoe I was adding some transformed targets like quantile transformed energy to the truth table using pandas to_sql. I thought the function just added the data to the table but in fact it just creates a new copy with the data and replaces the old but if you don't give it the schema of the table it will lose it primary key.

**Comment by RasmusOrsoe** [comment]
@MoustHolmes I'm glad you found the source of your troubles!

SQL is (in my opinion) a great format with just a few short-comings; one of them is that you **cannot** add columns to an existing table. The only way you can achieve this is by copying the table into memory, deleting the old table, and writing your data to a new table. This will inherently overwrite any existing schema. Besides, it's really not a good idea to begin altering the databases.

We have functionality that allows you to create new tables that are indexed correctly, if that is what you want to do; but in your use case I find that providing a transform to the **Task** is closer aligned with intended usage. 

I'm closing this issue. Feel free to re-open if I'm overseeing something.

**Comment by MoustHolmes** [comment]
I agree that altering the tables might not be optimal and my use case a transform could be used instead. but the point of graphnet is that other people should be able to use it and at some point someone will inevitably use some altered data. and if we say that you should only use databases generated using our utilities that we know works then whats the point of adding checks.
I think this is a prime example of where checks is useful when the code doesn't give a error but just doesn't run
