### ISSUE TITLE
implement use of SQLite VIEW for more performant queries  

### ISSUE THREAD

**Issue by MoustHolmes** [graphnet-team/graphnet#451]
In my quest of finde the cause of #440 I ran into the problem that decreasing the number of choose events_no in training did nothing for the query time even though the real reason for the bad performing run was the problem described in #450.
i suggest than when we make a selection  we also create a temporary view in the database that we uses when querying. This means that SQLite only have to look through the events in the selection instead of the whole database.  I'll be honest I don't know whether data loading is a bottle neck at the moment but as we increase the size of the databases  and the number of GPU's I would think we could gain some performance from this.

**Comment by RasmusOrsoe** [comment]
@MoustHolmes If you can write a minimum working example that checks current query speeds vs. your suggested method, I'd be happy to run it on some of the largest data samples we have available to verify numbers.

**Comment by MortenHolmRep** [comment]
@MoustHolmes I suggest you set up profiling from this [example](https://github.com/MortenHolmRep/graphnet/blob/profiling/examples/train_model_profiled.py).
That way, you can better see what function call or method creates the bottleneck. In the tests of the example script, I did at the time I did not encounter the performance you described.
