### ISSUE TITLE
Enable selection in `DatasetConfig` without dummy condition

### ISSUE THREAD

**Issue by BastianSetter** [graphnet-team/graphnet#493]
When creating a selection with:
`dataset.config.selection=("train":  "1000 random events ~ ...")`
it is currently not possible to give no condition, but a dummy condition has to be used.

**Comment by AMHermansen** [comment]
Hello @RasmusOrsoe and @BastianSetter this issue seems to imply manually changing a config file for a given training, in a similar fashion to #582 . Should we close this issue, since it falls outside intended use case?
