### ISSUE TITLE
Clarify dataset function name

### ISSUE THREAD

**Issue by BastianSetter** [graphnet-team/graphnet#497]
In graphnet/src/graphnet/data/dataset.py is written:
`def _get_all_indices(self) -> List[int]:
        """Return a list of all available values in 'self._index_column'."""`

In some datasets the events may have multiple rows describing the same event and therefore containing the same event_id. 
To avoid confusion , it may be good to include the keyword 'unique'.

**Comment by samadpls** [comment]
May I work on this @RasmusOrsoe

**Comment by RasmusOrsoe** [comment]
Yes @samadpls!
