### ISSUE TITLE
Make sure examples reflect intended usage

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#583]
Some of our current examples can give a misleading intended usage of the code base. .e.g #582. We should iterate through the examples and make sure we're not providing misunderstandings.

Here's a few things I've noticed:

1. Make sure that it's clear that config files are for reproducibility only. 
2. GenericExtractor is a special module thats slow and not a great place to start for data conversion.

**Comment by AMHermansen** [comment]
If we intend on updating the examples to better reflect the intended use-case then perhaps we should also update the readme, so it becomes clearer what the library aims to provide :smile: .
