### ISSUE TITLE
Should we refactor Model and StandardModel?

### ISSUE THREAD

**Issue by AMHermansen** [graphnet-team/graphnet#599]
Currently we have a lot of methods defined in the `Model` class, however since `Model` is a superclass of almost every commonly used class in GraphNeT, we get weird functionality, where a user is free to call methods like `predict, predict_as_dataframe, fit`etc. from classes like `Detector, GraphDefinition`. I'm not quite sure what the behavior would be, either you would get some nonsensical behavior or a runtime-error, all of these are marked as "public" methods and should be callable from any subclass of Model. Most of these methods are to my understanding only supposed to be called from a `StandardModel` instance. Hence I propose that we figure out what methods are essential for all our classes and which should be moved to the `StandardModel`.

**Describe the solution you'd like**
From a quick glance of the `Model` class I believe the only truly universal methods are:
`save, load, save_state_dict, load_state_dict, from_config`.
I think moving the remaining functions to StandardModel, would clean up the code, and remove weird behavior where a Detector class tries to call a fit function.

**Additional context**
Perhaps there are other methods, which are meaning full for all classes that I missed.

**Comment by RasmusOrsoe** [comment]
@AMHermansen I think this is a great idea.

I think we could do the following hand-over:

`Model`: A generic model class that is essentially a minimally-modified lightning model. For people who wants complete freedom. **No forward pass implementation.**
- modifications: `save`, `load`, `save_state_dict`, `load_state_dict`, `from_config`
- Optionally: Include in our modified version also the abstract methods such that it is clear at-a-glance which methods are available for implementation.

`StandardModel`: Inherits from `Model` - an implementation that seeks to make the syntax of training models in graphnet "sklearn-like". Forward pass implemented such that the class can do 99% of what people need - regression, classification. Advanced usage such as ensembling multiple model outputs etc. is left for other `Model` implementations.
- Public methods: `fit(..)`, `predict`, `predict_as_dataframe`

`StandardEnsembleModel`: Designed specifically for ensembling/stacking outputs from multiple `Models`. Overwrites forward pass of `StandardModel`.
- New args: `ensemble_members: List[Model]`, `freeze_ensemble_members: Bool`

I'll need ensembling functionality soon, so I'd be happy to give `StandardEnsembleModel` a crack. Would you be interested in working on the refactor? @AMHermansen
