### ISSUE TITLE
Should we remove PISA-related code?

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#671]
Currently, our library contain code that relies on PISA, an icecube software package for low energy oscillation analyses.

Because of closed data policies and execution times, this code cannot be subject to unit tests. In total, this is makes up around 1.200 lines of codes that we don't have tests for, which hurts our code coverage.

I think we should consider removing this code because:

- I don't think anyone is actively using it
- I don't think graphnet should contain code that we can't test
- The current fitting code in (https://github.com/graphnet-team/graphnet/blob/main/src/graphnet/pisa/fitting.py) doesn't  allow the users to include noise and muons, making it's usability very narrow. 
- Removing this code would contribute towards #102

**Comment by RasmusOrsoe** [comment]
@Aske-Rosted @kayla-leonard @AMHermansen do you have any opinions on this?

**Comment by Aske-Rosted** [comment]
I think the points that you are bringing up are quite reasonable. I am also not aware of anyone using the code. How about before removing the code creating a branch for archiving? Then if someone were using the functionality we could either refer to the branch or reinstate the code.

**Comment by kayla-leonard** [comment]
Yeah, I wasn't even aware this code existed and I can't think of a specific reason one would need this integration. I don't think graphnet benefits by having this pisa functionality.
