### ISSUE TITLE
Batch ParquetDataset by event rather than by file

### ISSUE THREAD

**Issue by OscarBarreraGithub** [graphnet-team/graphnet#731]
The [`_calculate_sizes`](https://github.com/graphnet-team/graphnet/blob/72c38d52fa39923bf5c6728b6ce347b224132f72/src/graphnet/data/dataset/parquet/parquet_dataset.py#L197) function (which calculates the number of events in each batch) within the `ParquetDataset` class calculates the batch size by appending the length of each file inside the batch.

It would be useful to batch by event rather than by file so we can process high energy events (which have many rows per event) without manually chunking the .parquet file beforehand (.parquet is well suited to handle large files anyway).

I am working on a fix by updating the way `query_table` batches events.

**Comment by RasmusOrsoe** [comment]
Hey @OscarBarreraGithub!

Could you elaborate a little on what you're suggesting here? The parquet files are packed in shuffled chunks of events and is not designed to provide fast, random access on a per-row level, like the SQLite format is well-suited for.

**Comment by OscarBarreraGithub** [comment]
Hey @RasmusOrsoe,

ah, I see. However, I was under the impression that the benefit of Parquet is that we can work with larger files (since they take up ~ 1/7th of the space of .db SQLite files). However, this then means that we can no longer batch by file as it will be too computationally expensive - especially for very high energy events.

My current workaround is to chunk my large Parquet files in a preprocessing step, and then feeding this directory to the trainer. Is this the optimal way (rather than batching by # of events in each file)?

**Comment by RasmusOrsoe** [comment]
The trade-off between parquet and sqlite in our context is basically this:
