### ISSUE TITLE
Add flowchart/infographic to repo

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#90]
I get a lot of questions of these types:

- Why do we need a Task Class?
- How does the Task Class fit together with the Model class and Training Class?

Once we get some spare time, I think it would be useful to write a FAQ and make some sort of infographic that shows how these things fit together

**Comment by asogaard** [comment]
With the addition of GETTING_STARTED.md, do you agree that the main purpose of this issue has been addressed, @RasmusOrsoe?

**Comment by RasmusOrsoe** [comment]
@asogaard in the context of v1.0.0, yes. I would still like to have a flow chart that shows how data flows through `Model` in high detail but I think this falls under #401 and we should probably not make such a graphic until #462 is settled and implemented.

**Comment by asogaard** [comment]
Sound like a plan!
